
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include <react/renderer/components/PasteTextInputSpecs/Props.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook::react {

PasteTextInputProps::PasteTextInputProps(
    const PropsParserContext &context,
    const PasteTextInputProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    allowFontScaling(convertRawProp(context, rawProps, "allowFontScaling", sourceProps.allowFontScaling, {false})),
    autoCapitalize(convertRawProp(context, rawProps, "autoCapitalize", sourceProps.autoCapitalize, {PasteTextInputAutoCapitalize::None})),
    autoComplete(convertRawProp(context, rawProps, "autoComplete", sourceProps.autoComplete, {PasteTextInputAutoComplete::Off})),
    autoCorrect(convertRawProp(context, rawProps, "autoCorrect", sourceProps.autoCorrect, {false})),
    autoFocus(convertRawProp(context, rawProps, "autoFocus", sourceProps.autoFocus, {false})),
    blurOnSubmit(convertRawProp(context, rawProps, "blurOnSubmit", sourceProps.blurOnSubmit, {false})),
    caretHidden(convertRawProp(context, rawProps, "caretHidden", sourceProps.caretHidden, {false})),
    clearButtonMode(convertRawProp(context, rawProps, "clearButtonMode", sourceProps.clearButtonMode, {})),
    clearTextOnFocus(convertRawProp(context, rawProps, "clearTextOnFocus", sourceProps.clearTextOnFocus, {false})),
    contextMenuHidden(convertRawProp(context, rawProps, "contextMenuHidden", sourceProps.contextMenuHidden, {false})),
    defaultValue(convertRawProp(context, rawProps, "defaultValue", sourceProps.defaultValue, {})),
    disableCopyPaste(convertRawProp(context, rawProps, "disableCopyPaste", sourceProps.disableCopyPaste, {false})),
    disableFullscreenUI(convertRawProp(context, rawProps, "disableFullscreenUI", sourceProps.disableFullscreenUI, {false})),
    editable(convertRawProp(context, rawProps, "editable", sourceProps.editable, {false})),
    enablesReturnKeyAutomatically(convertRawProp(context, rawProps, "enablesReturnKeyAutomatically", sourceProps.enablesReturnKeyAutomatically, {false})),
    importantForAutofill(convertRawProp(context, rawProps, "importantForAutofill", sourceProps.importantForAutofill, {})),
    inlineImageLeft(convertRawProp(context, rawProps, "inlineImageLeft", sourceProps.inlineImageLeft, {})),
    inlineImagePadding(convertRawProp(context, rawProps, "inlineImagePadding", sourceProps.inlineImagePadding, {0})),
    inputAccessoryViewID(convertRawProp(context, rawProps, "inputAccessoryViewID", sourceProps.inputAccessoryViewID, {})),
    keyboardAppearance(convertRawProp(context, rawProps, "keyboardAppearance", sourceProps.keyboardAppearance, {})),
    keyboardType(convertRawProp(context, rawProps, "keyboardType", sourceProps.keyboardType, {PasteTextInputKeyboardType::Default})),
    maxFontSizeMultiplier(convertRawProp(context, rawProps, "maxFontSizeMultiplier", sourceProps.maxFontSizeMultiplier, {0.0})),
    maxLength(convertRawProp(context, rawProps, "maxLength", sourceProps.maxLength, {0})),
    mostRecentEventCount(convertRawProp(context, rawProps, "mostRecentEventCount", sourceProps.mostRecentEventCount, {0})),
    multiline(convertRawProp(context, rawProps, "multiline", sourceProps.multiline, {false})),
    numberOfLines(convertRawProp(context, rawProps, "numberOfLines", sourceProps.numberOfLines, {0})),
    passwordRules(convertRawProp(context, rawProps, "passwordRules", sourceProps.passwordRules, {})),
    placeholder(convertRawProp(context, rawProps, "placeholder", sourceProps.placeholder, {})),
    placeholderTextColor(convertRawProp(context, rawProps, "placeholderTextColor", sourceProps.placeholderTextColor, {})),
    returnKeyLabel(convertRawProp(context, rawProps, "returnKeyLabel", sourceProps.returnKeyLabel, {})),
    returnKeyType(convertRawProp(context, rawProps, "returnKeyType", sourceProps.returnKeyType, {PasteTextInputReturnKeyType::Done})),
    scrollEnabled(convertRawProp(context, rawProps, "scrollEnabled", sourceProps.scrollEnabled, {false})),
    secureTextEntry(convertRawProp(context, rawProps, "secureTextEntry", sourceProps.secureTextEntry, {false})),
    selection(convertRawProp(context, rawProps, "selection", sourceProps.selection, {})),
    selectionColor(convertRawProp(context, rawProps, "selectionColor", sourceProps.selectionColor, {})),
    selectionHandleColor(convertRawProp(context, rawProps, "selectionHandleColor", sourceProps.selectionHandleColor, {})),
    selectTextOnFocus(convertRawProp(context, rawProps, "selectTextOnFocus", sourceProps.selectTextOnFocus, {false})),
    showSoftInputOnFocus(convertRawProp(context, rawProps, "showSoftInputOnFocus", sourceProps.showSoftInputOnFocus, {false})),
    smartInsertDelete(convertRawProp(context, rawProps, "smartInsertDelete", sourceProps.smartInsertDelete, {false})),
    smartPunctuation(convertRawProp(context, rawProps, "smartPunctuation", sourceProps.smartPunctuation, {})),
    spellCheck(convertRawProp(context, rawProps, "spellCheck", sourceProps.spellCheck, {false})),
    submitBehavior(convertRawProp(context, rawProps, "submitBehavior", sourceProps.submitBehavior, {PasteTextInputSubmitBehavior::Submit})),
    text(convertRawProp(context, rawProps, "text", sourceProps.text, {})),
    textBreakStrategy(convertRawProp(context, rawProps, "textBreakStrategy", sourceProps.textBreakStrategy, {PasteTextInputTextBreakStrategy::Simple})),
    textContentType(convertRawProp(context, rawProps, "textContentType", sourceProps.textContentType, {})),
    underlineColorAndroid(convertRawProp(context, rawProps, "underlineColorAndroid", sourceProps.underlineColorAndroid, {})),
    value(convertRawProp(context, rawProps, "value", sourceProps.value, {})),
    textShadowColor(convertRawProp(context, rawProps, "textShadowColor", sourceProps.textShadowColor, {})),
    textShadowRadius(convertRawProp(context, rawProps, "textShadowRadius", sourceProps.textShadowRadius, {0.0})),
    textDecorationLine(convertRawProp(context, rawProps, "textDecorationLine", sourceProps.textDecorationLine, {})),
    fontStyle(convertRawProp(context, rawProps, "fontStyle", sourceProps.fontStyle, {})),
    textShadowOffset(convertRawProp(context, rawProps, "textShadowOffset", sourceProps.textShadowOffset, {})),
    lineHeight(convertRawProp(context, rawProps, "lineHeight", sourceProps.lineHeight, {0.0})),
    textTransform(convertRawProp(context, rawProps, "textTransform", sourceProps.textTransform, {})),
    color(convertRawProp(context, rawProps, "color", sourceProps.color, {0})),
    letterSpacing(convertRawProp(context, rawProps, "letterSpacing", sourceProps.letterSpacing, {0.0})),
    fontSize(convertRawProp(context, rawProps, "fontSize", sourceProps.fontSize, {0.0})),
    textAlign(convertRawProp(context, rawProps, "textAlign", sourceProps.textAlign, {})),
    includeFontPadding(convertRawProp(context, rawProps, "includeFontPadding", sourceProps.includeFontPadding, {false})),
    fontWeight(convertRawProp(context, rawProps, "fontWeight", sourceProps.fontWeight, {})),
    fontFamily(convertRawProp(context, rawProps, "fontFamily", sourceProps.fontFamily, {})),
    textAlignVertical(convertRawProp(context, rawProps, "textAlignVertical", sourceProps.textAlignVertical, {})),
    cursorColor(convertRawProp(context, rawProps, "cursorColor", sourceProps.cursorColor, {}))
      {}

} // namespace facebook::react
