
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/PasteTextInputSpecs/EventEmitters.h>
#include <react/renderer/components/PasteTextInputSpecs/Props.h>
#include <react/renderer/components/PasteTextInputSpecs/States.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook::react {

JSI_EXPORT extern const char PasteTextInputComponentName[];

/*
 * `ShadowNode` for <PasteTextInput> component.
 */
using PasteTextInputShadowNode = ConcreteViewShadowNode<
    PasteTextInputComponentName,
    PasteTextInputProps,
    PasteTextInputEventEmitter,
    PasteTextInputState>;

} // namespace facebook::react
