
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeCpp.js
 */

#include <react/renderer/components/PasteTextInputSpecs/ShadowNodes.h>

namespace facebook::react {

extern const char PasteTextInputComponentName[] = "PasteTextInput";

} // namespace facebook::react
